import { dirname } from "path";
import { fileURLToPath } from "url";
import { FlatCompat } from "@eslint/eslintrc";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const compat = new FlatCompat({
  baseDirectory: __dirname,
});

const eslintConfig = [
  ...compat.extends("next/core-web-vitals", "next/typescript"),
  {
    rules: {
      "@typescript-eslint/no-explicit-any": "off",
      "@typescript-eslint/no-unused-vars": "off",
      "@typescript-eslint/no-var-requires": "off",
      "@typescript-eslint/ban-ts-comment": "off",
      "@typescript-eslint/no-non-null-assertion": "off",
      "@typescript-eslint/no-empty-function": "off",
      "prefer-const": "off",
      "react-hooks/exhaustive-deps": "off",
      "react-hooks/rules-of-hooks": "off",
      "no-unused-vars": "off",
      "no-console": "off",
      "no-undef": "off",
      "prefer-arrow-callback": "off",
      "react/no-unescaped-entities": "off",
      "react/display-name": "off",
      "react/jsx-key": "off",
      "react/jsx-no-target-blank": "off",
      "react/no-unknown-property": "off",
      "react/prop-types": "off",
      "react/react-in-jsx-scope": "off",
      "react/self-closing-comp": "off",
      "react/jsx-uses-react": "off",
      "react/jsx-uses-vars": "off",
      "import/no-anonymous-default-export": "off",
      "import/order": "off",
      "import/no-unresolved": "off",
      "import/named": "off",
      "import/default": "off",
      "import/namespace": "off",
      "import/no-duplicates": "off",
      "import/no-cycle": "off",
      "import/no-self-import": "off",
      "import/no-useless-path-segments": "off",
      "import/no-relative-parent-imports": "off",
      "import/no-unused-modules": "off",
      "import/no-commonjs": "off",
      "import/no-amd": "off",
      "import/no-nodejs-modules": "off",
      "import/no-extraneous-dependencies": "off",
      "import/no-mutable-exports": "off",
      "import/no-named-as-default": "off",
      "import/no-named-as-default-member": "off",
      "import/no-named-export": "off",
      "import/no-namespace": "off",
      "import/no-relative-imports": "off",
      "import/no-restricted-paths": "off",
      "import/no-unassigned-import": "off",
      "import/no-unused-modules": "off",
      "import/no-useless-path-segments": "off",
      "import/no-relative-parent-imports": "off",
      "import/no-self-import": "off",
      "import/no-cycle": "off",
      "import/no-duplicates": "off",
      "import/namespace": "off",
      "import/default": "off",
      "import/named": "off",
      "import/no-unresolved": "off",
      "import/order": "off",
      "import/no-anonymous-default-export": "off",
      "react/jsx-uses-vars": "off",
      "react/jsx-uses-react": "off",
      "react/self-closing-comp": "off",
      "react/react-in-jsx-scope": "off",
      "react/prop-types": "off",
      "react/no-unknown-property": "off",
      "react/jsx-no-target-blank": "off",
      "react/jsx-key": "off",
      "react/display-name": "off",
      "react/no-unescaped-entities": "off",
      "prefer-arrow-callback": "off",
      "no-undef": "off",
      "no-console": "off",
      "no-unused-vars": "off",
      "react-hooks/rules-of-hooks": "off",
      "react-hooks/exhaustive-deps": "off",
      "prefer-const": "off",
      "@typescript-eslint/no-empty-function": "off",
      "@typescript-eslint/no-non-null-assertion": "off",
      "@typescript-eslint/ban-ts-comment": "off",
      "@typescript-eslint/no-var-requires": "off",
      "@typescript-eslint/no-unused-vars": "off",
      "@typescript-eslint/no-explicit-any": "off",
    },
  },
];

export default eslintConfig;
